package be.cookit.pos.android.ui

import be.cookit.pos.android.domain.AppLanguage

data class UiStrings(
    val home: String,
    val pos: String,
    val orders: String,
    val kitchen: String,
    val delivery: String,
    val cash: String,
    val settings: String,
    val fiscality: String,
    val online: String,
    val offline: String,
    val newOrder: String,
    val dineIn: String,
    val takeaway: String,
    val deliveryType: String,
    val cart: String,
    val subtotal: String,
    val vatIncluded: String,
    val total: String,
    val checkout: String,
    val emptyCart: String,
    val chooseTable: String,
    val cashOpening: String,
    val cashOpeningHelp: String,
    val cashFund: String,
    val drawer: String,
    val startService: String,
    val activeSession: String,
    val refresh: String,
    val logout: String,
    val synchronization: String,
    val printers: String,
    val account: String,
    val permissions: String,
    val language: String,
    val printerHost: String,
    val printerPort: String,
    val testPrinter: String,
    val printerReady: String,
    val printerFailed: String,
    val orderPaid: String,
    val openCashFirst: String,
    val settingsHelp: String,
    val paymentTitle: String,
    val cashPayment: String,
    val cashPaymentHelp: String,
    val cardTerminalPayment: String,
    val terminalHelp: String,
    val terminalConfirmHelp: String,
    val confirmPayment: String,
    val retryPayment: String,
    val cancel: String,
    val pendingOrder: String,
    val selectionRequired: String,
    val kitchenFlowHelp: String,
    val noKitchenTickets: String,
    val nextStatus: String,
    val kitchenReceived: String,
    val kitchenConfirmed: String,
    val kitchenPreparing: String,
    val kitchenReady: String,
    val kitchenServed: String,
    val greeting: String,
    val dashboardTodayOrders: String,
    val dashboardTodayRevenue: String,
    val dashboardTodayCustomers: String,
    val dashboardAverageRevenue: String,
    val dashboardSinceYesterday: String,
    val dashboardSincePreviousMonth: String,
    val dashboardMonthlySales: String,
    val dashboardTodayOrdersList: String,
    val dashboardWaitingOrder: String,
    val ordersHelp: String,
    val paid: String,
    val justNow: String,
    val minutesAgo: String,
    val hoursAgo: String,
    val daysAgo: String,
    val sendToKitchen: String,
    val createKot: String,
    val kotCreateFailed: String,
    val deliveryFlowHelp: String,
    val noActiveDelivery: String,
    val deliveryDetails: String,
    val customerName: String,
    val customerPhone: String,
    val deliveryAddressLabel: String,
    val deliveryDriver: String,
    val deliveryFeeLabel: String,
    val noDeliveryDrivers: String,
    val save: String,
    val deliveryRequired: String,
    val deliveryLoadFailed: String,
    val statusDelivered: String,
    val statusInKitchen: String,
    val statusReady: String,
    val statusPreparing: String,
    val statusPlaced: String,
    val statusConfirmed: String,
    val statusCancelled: String,
    val statusBilled: String
)

fun strings(language: AppLanguage): UiStrings = when (language) {
    AppLanguage.FR -> UiStrings(
        home="Accueil", pos="Caisse", orders="Commandes", kitchen="Cuisine", delivery="Livraison",
        cash="Fond de caisse", settings="Réglages", fiscality="Fiscalité", online="En ligne", offline="Hors ligne",
        newOrder="Nouvelle commande", dineIn="Sur place", takeaway="À emporter", deliveryType="Livraison",
        cart="Panier", subtotal="Sous-total", vatIncluded="TVA incluse", total="Total", checkout="Encaisser",
        emptyCart="Panier vide", chooseTable="Table", cashOpening="Ouverture de caisse",
        cashOpeningHelp="Comptage du fond de caisse avant le service.", cashFund="FOND DE CAISSE",
        drawer="Ouvrir le tiroir", startService="Démarrer le service", activeSession="Session de caisse active",
        refresh="Rafraîchir", logout="Déconnexion", synchronization="Synchronisation", printers="Imprimantes",
        account="Compte", permissions="Permissions", language="Langue", printerHost="IP imprimante",
        printerPort="Port", testPrinter="Tester ESC/POS", printerReady="Imprimante joignable",
        printerFailed="Imprimante non joignable", orderPaid="Commande créée et encaissée",
        openCashFirst="Ouvrez d’abord une session de caisse.", settingsHelp="Session Cookit connectée • synchro toutes les 2 s",
        paymentTitle="Encaissement", cashPayment="Espèces", cashPaymentHelp="Paiement comptant et tiroir-caisse",
        cardTerminalPayment="Carte / terminal", terminalHelp="Terminal bancaire externe",
        terminalConfirmHelp="Effectuez d’abord le paiement sur le terminal, puis confirmez ici uniquement après autorisation.",
        confirmPayment="Confirmer le paiement",
        retryPayment="Réessayer le paiement", cancel="Annuler", pendingOrder="Commande en attente", selectionRequired="sélection requise",
        kitchenFlowHelp="Mettez à jour l’état ici : le client QR suit la même commande en temps réel.",
        noKitchenTickets="Aucun ticket cuisine actif", nextStatus="Passer à", kitchenReceived="Reçue",
        kitchenConfirmed="Confirmée", kitchenPreparing="En préparation", kitchenReady="Prête", kitchenServed="Servie",
        greeting="Bonjour", dashboardTodayOrders="Commandes du jour", dashboardTodayRevenue="Revenus du jour",
        dashboardTodayCustomers="Clients du jour", dashboardAverageRevenue="Revenu quotidien moyen",
        dashboardSinceYesterday="depuis hier", dashboardSincePreviousMonth="depuis le mois précédent",
        dashboardMonthlySales="Ventes ce mois-ci", dashboardTodayOrdersList="Commandes aujourd’hui",
        dashboardWaitingOrder="En attente de la première commande d’aujourd’hui",
        ordersHelp="Touchez une commande non payée pour la rouvrir dans la caisse.", paid="Payé",
        justNow="à l’instant", minutesAgo="il y a {n} min", hoursAgo="il y a {n} h", daysAgo="il y a {n} j",
        sendToKitchen="Envoyer en cuisine (KOT)", createKot="Créer KOT", kotCreateFailed="Impossible de créer le KOT.",
        deliveryFlowHelp="Commandes de livraison internes et plateformes dans le même flux.", noActiveDelivery="Aucune livraison active",
        deliveryDetails="Détails de livraison", customerName="Nom du client", customerPhone="Téléphone",
        deliveryAddressLabel="Adresse de livraison", deliveryDriver="Livreur", deliveryFeeLabel="Frais de livraison",
        noDeliveryDrivers="Aucun livreur disponible", save="Enregistrer",
        deliveryRequired="Adresse et livreur requis.", deliveryLoadFailed="Impossible de charger les paramètres de livraison.",
        statusDelivered="Livré", statusInKitchen="En cuisine", statusReady="Prêt", statusPreparing="En préparation",
        statusPlaced="Reçue", statusConfirmed="Confirmée", statusCancelled="Annulée", statusBilled="Facturée"
    )
    AppLanguage.NL -> UiStrings(
        home="Start", pos="Kassa", orders="Bestellingen", kitchen="Keuken", delivery="Levering",
        cash="Kasgeld", settings="Instellingen", fiscality="Fiscaliteit", online="Online", offline="Offline",
        newOrder="Nieuwe bestelling", dineIn="Ter plaatse", takeaway="Afhalen", deliveryType="Levering",
        cart="Winkelmand", subtotal="Subtotaal", vatIncluded="Btw inbegrepen", total="Totaal", checkout="Afrekenen",
        emptyCart="Winkelmand leeg", chooseTable="Tafel", cashOpening="Kassa openen",
        cashOpeningHelp="Tel het startbedrag voor de dienst.", cashFund="KASGELD",
        drawer="Kassalade openen", startService="Dienst starten", activeSession="Actieve kassasessie",
        refresh="Vernieuwen", logout="Afmelden", synchronization="Synchronisatie", printers="Printers",
        account="Account", permissions="Rechten", language="Taal", printerHost="Printer-IP",
        printerPort="Poort", testPrinter="ESC/POS testen", printerReady="Printer bereikbaar",
        printerFailed="Printer niet bereikbaar", orderPaid="Bestelling aangemaakt en betaald",
        openCashFirst="Open eerst een kassasessie.", settingsHelp="Cookit-sessie verbonden • sync elke 2 s",
        paymentTitle="Betaling", cashPayment="Contant", cashPaymentHelp="Contante betaling en kassalade",
        cardTerminalPayment="Kaart / terminal", terminalHelp="Externe betaalterminal",
        terminalConfirmHelp="Voer eerst de betaling uit op de terminal en bevestig hier pas na goedkeuring.",
        confirmPayment="Betaling bevestigen",
        retryPayment="Betaling opnieuw proberen", cancel="Annuleren", pendingOrder="Wachtende bestelling", selectionRequired="selectie vereist",
        kitchenFlowHelp="Werk de status hier bij: de QR-klant volgt dezelfde bestelling in realtime.",
        noKitchenTickets="Geen actieve keukentickets", nextStatus="Naar", kitchenReceived="Ontvangen",
        kitchenConfirmed="Bevestigd", kitchenPreparing="In bereiding", kitchenReady="Klaar", kitchenServed="Geserveerd",
        greeting="Hallo", dashboardTodayOrders="Bestellingen van vandaag", dashboardTodayRevenue="Omzet van vandaag",
        dashboardTodayCustomers="Klanten van vandaag", dashboardAverageRevenue="Gemiddelde dagomzet",
        dashboardSinceYesterday="sinds gisteren", dashboardSincePreviousMonth="sinds vorige maand",
        dashboardMonthlySales="Verkoop deze maand", dashboardTodayOrdersList="Bestellingen vandaag",
        dashboardWaitingOrder="Wachten op de eerste bestelling van vandaag",
        ordersHelp="Tik op een onbetaalde bestelling om ze opnieuw in de kassa te openen.", paid="Betaald",
        justNow="zojuist", minutesAgo="{n} min geleden", hoursAgo="{n} u geleden", daysAgo="{n} d geleden",
        sendToKitchen="Naar keuken sturen (KOT)", createKot="KOT maken", kotCreateFailed="KOT kon niet worden aangemaakt.",
        deliveryFlowHelp="Interne leveringen en platformbestellingen in één stroom.", noActiveDelivery="Geen actieve leveringen",
        deliveryDetails="Leveringsgegevens", customerName="Naam klant", customerPhone="Telefoon",
        deliveryAddressLabel="Leveringsadres", deliveryDriver="Koerier", deliveryFeeLabel="Leveringskosten",
        noDeliveryDrivers="Geen koerier beschikbaar", save="Opslaan",
        deliveryRequired="Adres en koerier zijn verplicht.", deliveryLoadFailed="Leveringsinstellingen konden niet worden geladen.",
        statusDelivered="Geleverd", statusInKitchen="In keuken", statusReady="Klaar", statusPreparing="In bereiding",
        statusPlaced="Ontvangen", statusConfirmed="Bevestigd", statusCancelled="Geannuleerd", statusBilled="Gefactureerd"
    )
    AppLanguage.EN -> UiStrings(
        home="Home", pos="POS", orders="Orders", kitchen="Kitchen", delivery="Delivery",
        cash="Cash drawer", settings="Settings", fiscality="Fiscality", online="Online", offline="Offline",
        newOrder="New order", dineIn="Dine in", takeaway="Takeaway", deliveryType="Delivery",
        cart="Cart", subtotal="Subtotal", vatIncluded="VAT included", total="Total", checkout="Charge",
        emptyCart="Cart is empty", chooseTable="Table", cashOpening="Open cash register",
        cashOpeningHelp="Count the opening float before service.", cashFund="OPENING FLOAT",
        drawer="Open drawer", startService="Start service", activeSession="Active cash session",
        refresh="Refresh", logout="Sign out", synchronization="Synchronization", printers="Printers",
        account="Account", permissions="Permissions", language="Language", printerHost="Printer IP",
        printerPort="Port", testPrinter="Test ESC/POS", printerReady="Printer reachable",
        printerFailed="Printer unreachable", orderPaid="Order created and paid",
        openCashFirst="Open a cash session first.", settingsHelp="Cookit session connected • sync every 2 s",
        paymentTitle="Payment", cashPayment="Cash", cashPaymentHelp="Cash payment and drawer",
        cardTerminalPayment="Card / terminal", terminalHelp="External payment terminal",
        terminalConfirmHelp="Complete the payment on the terminal first, then confirm here only after approval.",
        confirmPayment="Confirm payment",
        retryPayment="Retry payment", cancel="Cancel", pendingOrder="Pending order", selectionRequired="selection required",
        kitchenFlowHelp="Update the status here: QR customers follow the same order in real time.",
        noKitchenTickets="No active kitchen tickets", nextStatus="Move to", kitchenReceived="Received",
        kitchenConfirmed="Confirmed", kitchenPreparing="Preparing", kitchenReady="Ready", kitchenServed="Served",
        greeting="Hello", dashboardTodayOrders="Today’s orders", dashboardTodayRevenue="Today’s revenue",
        dashboardTodayCustomers="Today’s customers", dashboardAverageRevenue="Average daily revenue",
        dashboardSinceYesterday="since yesterday", dashboardSincePreviousMonth="since previous month",
        dashboardMonthlySales="Sales this month", dashboardTodayOrdersList="Today’s orders",
        dashboardWaitingOrder="Waiting for today’s first order",
        ordersHelp="Tap an unpaid order to reopen it in the POS.", paid="Paid",
        justNow="just now", minutesAgo="{n} min ago", hoursAgo="{n} h ago", daysAgo="{n} d ago",
        sendToKitchen="Send to kitchen (KOT)", createKot="Create KOT", kotCreateFailed="Could not create the KOT.",
        deliveryFlowHelp="Internal delivery and platform orders in the same flow.", noActiveDelivery="No active deliveries",
        deliveryDetails="Delivery details", customerName="Customer name", customerPhone="Phone",
        deliveryAddressLabel="Delivery address", deliveryDriver="Driver", deliveryFeeLabel="Delivery fee",
        noDeliveryDrivers="No driver available", save="Save",
        deliveryRequired="Address and driver are required.", deliveryLoadFailed="Could not load delivery settings.",
        statusDelivered="Delivered", statusInKitchen="In kitchen", statusReady="Ready", statusPreparing="Preparing",
        statusPlaced="Received", statusConfirmed="Confirmed", statusCancelled="Cancelled", statusBilled="Billed"
    )
    AppLanguage.DE -> UiStrings(
        home="Start", pos="Kasse", orders="Bestellungen", kitchen="Küche", delivery="Lieferung",
        cash="Kassenbestand", settings="Einstellungen", fiscality="Fiskalität", online="Online", offline="Offline",
        newOrder="Neue Bestellung", dineIn="Vor Ort", takeaway="Abholung", deliveryType="Lieferung",
        cart="Warenkorb", subtotal="Zwischensumme", vatIncluded="MwSt. inkl.", total="Gesamt", checkout="Kassieren",
        emptyCart="Warenkorb leer", chooseTable="Tisch", cashOpening="Kasse öffnen",
        cashOpeningHelp="Anfangsbestand vor dem Service zählen.", cashFund="KASSENBESTAND",
        drawer="Kassenschublade öffnen", startService="Service starten", activeSession="Aktive Kassensitzung",
        refresh="Aktualisieren", logout="Abmelden", synchronization="Synchronisierung", printers="Drucker",
        account="Konto", permissions="Berechtigungen", language="Sprache", printerHost="Drucker-IP",
        printerPort="Port", testPrinter="ESC/POS testen", printerReady="Drucker erreichbar",
        printerFailed="Drucker nicht erreichbar", orderPaid="Bestellung erstellt und bezahlt",
        openCashFirst="Öffnen Sie zuerst eine Kassensitzung.", settingsHelp="Cookit verbunden • Sync alle 2 s",
        paymentTitle="Zahlung", cashPayment="Bar", cashPaymentHelp="Barzahlung und Kassenschublade",
        cardTerminalPayment="Karte / Terminal", terminalHelp="Externes Zahlungsterminal",
        terminalConfirmHelp="Führen Sie zuerst die Zahlung am Terminal durch und bestätigen Sie hier erst nach Freigabe.",
        confirmPayment="Zahlung bestätigen",
        retryPayment="Zahlung wiederholen", cancel="Abbrechen", pendingOrder="Offene Bestellung", selectionRequired="Auswahl erforderlich",
        kitchenFlowHelp="Status hier aktualisieren: QR-Kunden verfolgen dieselbe Bestellung in Echtzeit.",
        noKitchenTickets="Keine aktiven Küchentickets", nextStatus="Weiter zu", kitchenReceived="Eingegangen",
        kitchenConfirmed="Bestätigt", kitchenPreparing="In Zubereitung", kitchenReady="Bereit", kitchenServed="Serviert",
        greeting="Hallo", dashboardTodayOrders="Heutige Bestellungen", dashboardTodayRevenue="Heutiger Umsatz",
        dashboardTodayCustomers="Heutige Kunden", dashboardAverageRevenue="Durchschnittlicher Tagesumsatz",
        dashboardSinceYesterday="seit gestern", dashboardSincePreviousMonth="seit dem Vormonat",
        dashboardMonthlySales="Verkäufe diesen Monat", dashboardTodayOrdersList="Heutige Bestellungen",
        dashboardWaitingOrder="Warten auf die erste Bestellung des Tages",
        ordersHelp="Tippen Sie auf eine unbezahlte Bestellung, um sie in der Kasse wieder zu öffnen.", paid="Bezahlt",
        justNow="gerade eben", minutesAgo="vor {n} Min.", hoursAgo="vor {n} Std.", daysAgo="vor {n} T.",
        sendToKitchen="An Küche senden (KOT)", createKot="KOT erstellen", kotCreateFailed="KOT konnte nicht erstellt werden.",
        deliveryFlowHelp="Interne Lieferungen und Plattformbestellungen in einem Ablauf.", noActiveDelivery="Keine aktiven Lieferungen",
        deliveryDetails="Lieferdetails", customerName="Kundenname", customerPhone="Telefon",
        deliveryAddressLabel="Lieferadresse", deliveryDriver="Fahrer", deliveryFeeLabel="Liefergebühr",
        noDeliveryDrivers="Kein Fahrer verfügbar", save="Speichern",
        deliveryRequired="Adresse und Fahrer sind erforderlich.", deliveryLoadFailed="Liefereinstellungen konnten nicht geladen werden.",
        statusDelivered="Geliefert", statusInKitchen="In Küche", statusReady="Bereit", statusPreparing="In Zubereitung",
        statusPlaced="Eingegangen", statusConfirmed="Bestätigt", statusCancelled="Storniert", statusBilled="Abgerechnet"
    )
}

data class FiscalUiStrings(
    val centerTitle: String,
    val centerSubtitle: String,
    val summaryTitle: String,
    val openCenter: String,
    val overview: String,
    val systemOperational: String,
    val systemAttention: String,
    val cloud: String,
    val fdm: String,
    val agent: String,
    val jobs: String,
    val connected: String,
    val offline: String,
    val running: String,
    val stopped: String,
    val pending: String,
    val autoStart: String,
    val lastHeartbeat: String,
    val lastPoll: String,
    val lastReceipt: String,
    val provider: String,
    val connection: String,
    val testConnection: String,
    val testTools: String,
    val testLastEvent: String,
    val verifyAdapterGate: String,
    val save: String,
    val host: String,
    val port: String,
    val mockMode: String,
    val restart: String,
    val configured: String,
    val notConfigured: String,
    val fiscalAgent: String,
    val deviceProvisioned: String,
    val deviceNotProvisioned: String,
    val deviceId: String,
    val deviceToken: String,
    val saveSecurely: String,
    val handshake: String,
    val heartbeat: String,
    val processOneJob: String,
    val startAuto: String,
    val stopAuto: String,
    val clearCredentials: String,
    val health: String,
    val activeJob: String,
    val phase: String,
    val failures: String,
    val pendingOutcomes: String,
    val watchdog: String,
    val wakeLock: String,
    val diagnostics: String,
    val recentActivity: String,
    val noActivity: String,
    val exportDiagnostic: String,
    val clearHistory: String,
    val exporting: String,
    val exportReady: String,
    val exportFailed: String,
    val historyCleared: String,
    val deviceResilience: String,
    val backgroundExecution: String,
    val screenOffProtection: String,
    val rebootRecovery: String,
    val durableJournal: String,
    val enabled: String,
    val disabled: String,
    val advanced: String,
    val runtimeId: String,
    val terminalId: String,
    val androidPosTitle: String,
    val androidPosSubtitle: String,
    val posAssignmentStatus: String,
    val posDeviceId: String,
    val assignThisPos: String,
    val refreshPosAssignment: String,
    val posUnassigned: String,
    val posPendingApproval: String,
    val posAssigned: String,
    val posDeclined: String,
    val posUnavailable: String,
    val localRuntime: String,
    val profileDisabled: String,
    val testMode: String,
    val productionMode: String,
    val retryPolicy: String,
    val retryDisposition: String,
    val retryAttempt: String,
    val nextRetry: String,
    val terminalFailures: String,
    val lastTerminalJob: String,
    val manualHoldTitle: String,
    val manualHoldMessage: String,
    val resumeProcessing: String
)

fun fiscalStrings(language: AppLanguage): FiscalUiStrings = when (language) {
    AppLanguage.FR -> FiscalUiStrings(
        centerTitle="Fiscalité", centerSubtitle="Centre fiscal de la branche", summaryTitle="Fiscalité & FDM",
        openCenter="Ouvrir le centre fiscal", overview="Vue d’ensemble", systemOperational="Système fiscal opérationnel",
        systemAttention="Attention requise", cloud="Cookit Cloud", fdm="FDM", agent="Agent Android", jobs="Jobs fiscaux",
        connected="Connecté", offline="Hors ligne", running="En cours", stopped="Arrêté", pending="En attente",
        autoStart="Démarrage automatique", lastHeartbeat="Dernier heartbeat", lastPoll="Dernier poll", lastReceipt="Dernier reçu",
        provider="Provider", connection="Connexion", testConnection="Tester la connexion", testTools="Outils de test", testLastEvent="Tester le dernier événement", verifyAdapterGate="Vérifier l’adapter", save="Enregistrer", host="Hôte / IP",
        port="Port", mockMode="Mode Mock", restart="Redémarrer", configured="Configuré", notConfigured="Non configuré",
        fiscalAgent="Fiscal Agent", deviceProvisioned="Appareil provisionné", deviceNotProvisioned="Appareil non provisionné",
        deviceId="Device ID", deviceToken="Device token", saveSecurely="Enregistrer sécurisé", handshake="Handshake",
        heartbeat="Heartbeat", processOneJob="Traiter 1 job", startAuto="Démarrer auto", stopAuto="Arrêter auto",
        clearCredentials="Effacer les identifiants", health="Santé", activeJob="Job actif", phase="Phase", failures="Échecs consécutifs",
        pendingOutcomes="Outcomes en attente", watchdog="Watchdog", wakeLock="Wake lock", diagnostics="Diagnostics",
        recentActivity="Activité récente", noActivity="Aucune activité récente", exportDiagnostic="Exporter le diagnostic",
        clearHistory="Effacer l’historique", exporting="Export en cours…", exportReady="Diagnostic prêt à partager",
        exportFailed="Échec de l’export", historyCleared="Historique effacé", deviceResilience="Résilience de l’appareil",
        backgroundExecution="Exécution en arrière-plan", screenOffProtection="Protection écran éteint",
        rebootRecovery="Reprise après redémarrage", durableJournal="Journal FDM durable", enabled="Actif", disabled="Inactif",
        advanced="Informations avancées", runtimeId="Runtime ID", terminalId="Terminal ID", androidPosTitle="Caisse Android", androidPosSubtitle="Affectation de cet appareil à la caisse Cookit", posAssignmentStatus="Statut de la caisse", posDeviceId="Identifiant de l’appareil", assignThisPos="Affecter cette caisse", refreshPosAssignment="Actualiser le statut", posUnassigned="Non affectée", posPendingApproval="En attente d’approbation", posAssigned="Affectée", posDeclined="Affectation refusée", posUnavailable="Indisponible", localRuntime="Runtime fiscal local",
        profileDisabled="Profil fiscal cloud désactivé", testMode="Mode test", productionMode="Mode production", retryPolicy="Politique de reprise", retryDisposition="Décision", retryAttempt="Tentative", nextRetry="Prochaine reprise", terminalFailures="Échecs terminaux", lastTerminalJob="Dernier job terminal", manualHoldTitle="Traitement fiscal suspendu", manualHoldMessage="Une intervention administrateur est requise avant de reprendre les jobs fiscaux.", resumeProcessing="Reprendre le traitement"
    )
    AppLanguage.NL -> FiscalUiStrings(
        centerTitle="Fiscaliteit", centerSubtitle="Fiscaal centrum van de vestiging", summaryTitle="Fiscaliteit & FDM",
        openCenter="Fiscaal centrum openen", overview="Overzicht", systemOperational="Fiscaal systeem operationeel",
        systemAttention="Aandacht vereist", cloud="Cookit Cloud", fdm="FDM", agent="Android-agent", jobs="Fiscale jobs",
        connected="Verbonden", offline="Offline", running="Actief", stopped="Gestopt", pending="In behandeling",
        autoStart="Automatisch starten", lastHeartbeat="Laatste heartbeat", lastPoll="Laatste poll", lastReceipt="Laatste ontvangst",
        provider="Provider", connection="Verbinding", testConnection="Verbinding testen", testTools="Testtools", testLastEvent="Laatste event testen", verifyAdapterGate="Adapter controleren", save="Opslaan", host="Host / IP",
        port="Poort", mockMode="Mock-modus", restart="Herstarten", configured="Geconfigureerd", notConfigured="Niet geconfigureerd",
        fiscalAgent="Fiscal Agent", deviceProvisioned="Apparaat voorzien", deviceNotProvisioned="Apparaat niet voorzien",
        deviceId="Device ID", deviceToken="Device token", saveSecurely="Veilig opslaan", handshake="Handshake",
        heartbeat="Heartbeat", processOneJob="1 job verwerken", startAuto="Auto starten", stopAuto="Auto stoppen",
        clearCredentials="Identificatie wissen", health="Gezondheid", activeJob="Actieve job", phase="Fase", failures="Opeenvolgende fouten",
        pendingOutcomes="Wachtende outcomes", watchdog="Watchdog", wakeLock="Wake lock", diagnostics="Diagnostiek",
        recentActivity="Recente activiteit", noActivity="Geen recente activiteit", exportDiagnostic="Diagnostiek exporteren",
        clearHistory="Geschiedenis wissen", exporting="Export bezig…", exportReady="Diagnostiek klaar om te delen",
        exportFailed="Export mislukt", historyCleared="Geschiedenis gewist", deviceResilience="Apparaatbestendigheid",
        backgroundExecution="Achtergronduitvoering", screenOffProtection="Bescherming bij uitgeschakeld scherm",
        rebootRecovery="Herstel na herstart", durableJournal="Duurzaam FDM-logboek", enabled="Actief", disabled="Inactief",
        advanced="Geavanceerde informatie", runtimeId="Runtime ID", terminalId="Terminal ID", androidPosTitle="Android-kassa", androidPosSubtitle="Dit apparaat aan de Cookit-kassa koppelen", posAssignmentStatus="Kassastatus", posDeviceId="Apparaat-ID", assignThisPos="Deze kassa koppelen", refreshPosAssignment="Status vernieuwen", posUnassigned="Niet gekoppeld", posPendingApproval="Wacht op goedkeuring", posAssigned="Gekoppeld", posDeclined="Koppeling geweigerd", posUnavailable="Niet beschikbaar", localRuntime="Lokale fiscale runtime",
        profileDisabled="Cloud fiscaal profiel uitgeschakeld", testMode="Testmodus", productionMode="Productiemodus", retryPolicy="Herstelbeleid", retryDisposition="Beslissing", retryAttempt="Poging", nextRetry="Volgende poging", terminalFailures="Definitieve fouten", lastTerminalJob="Laatste definitieve job", manualHoldTitle="Fiscale verwerking gepauzeerd", manualHoldMessage="Een beheerder moet ingrijpen voordat fiscale jobs worden hervat.", resumeProcessing="Verwerking hervatten"
    )
    AppLanguage.EN -> FiscalUiStrings(
        centerTitle="Fiscality", centerSubtitle="Branch fiscal control center", summaryTitle="Fiscality & FDM",
        openCenter="Open fiscal center", overview="Overview", systemOperational="Fiscal system operational",
        systemAttention="Attention required", cloud="Cookit Cloud", fdm="FDM", agent="Android agent", jobs="Fiscal jobs",
        connected="Connected", offline="Offline", running="Running", stopped="Stopped", pending="Pending",
        autoStart="Automatic start", lastHeartbeat="Last heartbeat", lastPoll="Last poll", lastReceipt="Last receipt",
        provider="Provider", connection="Connection", testConnection="Test connection", testTools="Test tools", testLastEvent="Test last event", verifyAdapterGate="Verify adapter", save="Save", host="Host / IP",
        port="Port", mockMode="Mock mode", restart="Restart", configured="Configured", notConfigured="Not configured",
        fiscalAgent="Fiscal Agent", deviceProvisioned="Device provisioned", deviceNotProvisioned="Device not provisioned",
        deviceId="Device ID", deviceToken="Device token", saveSecurely="Save securely", handshake="Handshake",
        heartbeat="Heartbeat", processOneJob="Process 1 job", startAuto="Start auto", stopAuto="Stop auto",
        clearCredentials="Clear credentials", health="Health", activeJob="Active job", phase="Phase", failures="Consecutive failures",
        pendingOutcomes="Pending outcomes", watchdog="Watchdog", wakeLock="Wake lock", diagnostics="Diagnostics",
        recentActivity="Recent activity", noActivity="No recent activity", exportDiagnostic="Export diagnostic",
        clearHistory="Clear history", exporting="Exporting…", exportReady="Diagnostic ready to share",
        exportFailed="Export failed", historyCleared="History cleared", deviceResilience="Device resilience",
        backgroundExecution="Background execution", screenOffProtection="Screen-off protection",
        rebootRecovery="Reboot recovery", durableJournal="Durable FDM journal", enabled="Enabled", disabled="Disabled",
        advanced="Advanced information", runtimeId="Runtime ID", terminalId="Terminal ID", androidPosTitle="Android POS", androidPosSubtitle="Assign this device to the Cookit POS", posAssignmentStatus="POS assignment status", posDeviceId="Device ID", assignThisPos="Assign this POS", refreshPosAssignment="Refresh status", posUnassigned="Not assigned", posPendingApproval="Awaiting approval", posAssigned="Assigned", posDeclined="Assignment declined", posUnavailable="Unavailable", localRuntime="Local fiscal runtime",
        profileDisabled="Cloud fiscal profile disabled", testMode="Test mode", productionMode="Production mode", retryPolicy="Retry policy", retryDisposition="Decision", retryAttempt="Attempt", nextRetry="Next retry", terminalFailures="Terminal failures", lastTerminalJob="Last terminal job", manualHoldTitle="Fiscal processing paused", manualHoldMessage="Administrator action is required before fiscal jobs can resume.", resumeProcessing="Resume processing"
    )
    AppLanguage.DE -> FiscalUiStrings(
        centerTitle="Fiskalität", centerSubtitle="Fiskalzentrum der Filiale", summaryTitle="Fiskalität & FDM",
        openCenter="Fiskalzentrum öffnen", overview="Übersicht", systemOperational="Fiskalsystem betriebsbereit",
        systemAttention="Aufmerksamkeit erforderlich", cloud="Cookit Cloud", fdm="FDM", agent="Android-Agent", jobs="Fiskal-Jobs",
        connected="Verbunden", offline="Offline", running="Aktiv", stopped="Gestoppt", pending="Ausstehend",
        autoStart="Automatischer Start", lastHeartbeat="Letzter Heartbeat", lastPoll="Letzter Poll", lastReceipt="Letzter Beleg",
        provider="Provider", connection="Verbindung", testConnection="Verbindung testen", testTools="Testwerkzeuge", testLastEvent="Letztes Ereignis testen", verifyAdapterGate="Adapter prüfen", save="Speichern", host="Host / IP",
        port="Port", mockMode="Mock-Modus", restart="Neu starten", configured="Konfiguriert", notConfigured="Nicht konfiguriert",
        fiscalAgent="Fiscal Agent", deviceProvisioned="Gerät provisioniert", deviceNotProvisioned="Gerät nicht provisioniert",
        deviceId="Device ID", deviceToken="Device token", saveSecurely="Sicher speichern", handshake="Handshake",
        heartbeat="Heartbeat", processOneJob="1 Job verarbeiten", startAuto="Auto starten", stopAuto="Auto stoppen",
        clearCredentials="Zugangsdaten löschen", health="Zustand", activeJob="Aktiver Job", phase="Phase", failures="Aufeinanderfolgende Fehler",
        pendingOutcomes="Ausstehende Outcomes", watchdog="Watchdog", wakeLock="Wake lock", diagnostics="Diagnose",
        recentActivity="Letzte Aktivität", noActivity="Keine aktuelle Aktivität", exportDiagnostic="Diagnose exportieren",
        clearHistory="Verlauf löschen", exporting="Export läuft…", exportReady="Diagnose bereit zum Teilen",
        exportFailed="Export fehlgeschlagen", historyCleared="Verlauf gelöscht", deviceResilience="Geräteresilienz",
        backgroundExecution="Hintergrundausführung", screenOffProtection="Schutz bei ausgeschaltetem Bildschirm",
        rebootRecovery="Wiederherstellung nach Neustart", durableJournal="Dauerhaftes FDM-Journal", enabled="Aktiv", disabled="Inaktiv",
        advanced="Erweiterte Informationen", runtimeId="Runtime ID", terminalId="Terminal ID", androidPosTitle="Android-Kasse", androidPosSubtitle="Dieses Gerät der Cookit-Kasse zuweisen", posAssignmentStatus="Kassenzuweisung", posDeviceId="Geräte-ID", assignThisPos="Diese Kasse zuweisen", refreshPosAssignment="Status aktualisieren", posUnassigned="Nicht zugewiesen", posPendingApproval="Wartet auf Genehmigung", posAssigned="Zugewiesen", posDeclined="Zuweisung abgelehnt", posUnavailable="Nicht verfügbar", localRuntime="Lokale Fiskal-Runtime",
        profileDisabled="Cloud-Fiskalprofil deaktiviert", testMode="Testmodus", productionMode="Produktionsmodus", retryPolicy="Wiederholungsrichtlinie", retryDisposition="Entscheidung", retryAttempt="Versuch", nextRetry="Nächster Versuch", terminalFailures="Endgültige Fehler", lastTerminalJob="Letzter endgültiger Job", manualHoldTitle="Fiskalverarbeitung pausiert", manualHoldMessage="Vor der Fortsetzung fiskaler Jobs ist eine Administratoraktion erforderlich.", resumeProcessing="Verarbeitung fortsetzen"
    )
}
