package be.cookit.pos.android.ui

import be.cookit.pos.android.domain.AppLanguage

data class RefundStrings(
    val refund: String,
    val title: String,
    val intro: String,
    val payment: String,
    val reason: String,
    val chooseReason: String,
    val full: String,
    val partial: String,
    val waste: String,
    val wasteHelp: String,
    val settlementHelp: String,
    val half: String,
    val fixed: String,
    val custom: String,
    val amount: String,
    val notes: String,
    val confirm: String,
    val close: String,
    val fiscalBlocked: String,
    val fiscalFullUnsupported: String,
    val fiscalPartialUnsupported: String,
    val fiscalPending: String,
    val fiscalFailed: String,
    val loyaltyBlocked: String,
    val loyaltyPartialUnsupported: String,
    val alreadyProcessed: String,
    val notAllowed: String,
    val reasonRequired: String,
    val paymentRequired: String,
    val amountInvalid: String,
    val processed: String,
    val wasteProcessed: String,
    val refunded: String,
    val writtenOff: String
)

fun refundStrings(language: AppLanguage): RefundStrings = when (language) {
    AppLanguage.FR -> RefundStrings(
        refund = "Rembourser",
        title = "Remboursement / perte",
        intro = "Cookit Cloud orchestre les remboursements complets éligibles : correction FDM d’abord, puis réversion fidélité compensatoire. Les remboursements partiels fiscalisés ou avec fidélité restent bloqués.",
        payment = "Paiement",
        reason = "Motif",
        chooseReason = "Choisir un motif",
        full = "Complet",
        partial = "Partiel",
        waste = "Perte / waste",
        wasteHelp = "Perte interne uniquement : aucun argent n’est rendu au client.",
        settlementHelp = "Paiement carte/terminal : effectuez d’abord le remboursement sur le terminal ou PSP externe. Cookit enregistre ensuite l’opération.",
        half = "Moitié",
        fixed = "Montant fixe",
        custom = "Personnalisé",
        amount = "Montant",
        notes = "Notes",
        confirm = "Confirmer",
        close = "Fermer",
        fiscalBlocked = "Correction fiscale requise avant remboursement.",
        fiscalFullUnsupported = "Cette vente fiscalisée n’est pas éligible au remboursement complet P3B (certification, paiement unique, composition compatible requise).",
        fiscalPartialUnsupported = "Le remboursement partiel d’une vente fiscalisée reste bloqué jusqu’à l’allocation exacte lignes/quantités.",
        fiscalPending = "Correction fiscale envoyée au FDM. Cookit finalisera le remboursement après fiscalisation ; vous pouvez laisser cet écran ouvert.",
        fiscalFailed = "La correction fiscale de remboursement est en échec. Résolvez la transaction fiscale avant de rendre l’argent au client.",
        loyaltyBlocked = "Réversion fidélité exacte requise avant remboursement.",
        loyaltyPartialUnsupported = "Le remboursement partiel avec fidélité reste bloqué jusqu’à une réversion proportionnelle exacte.",
        alreadyProcessed = "Un remboursement/perte a déjà été enregistré pour ce paiement.",
        notAllowed = "Ce remboursement n’est pas autorisé dans l’état actuel.",
        reasonRequired = "Choisissez un motif.",
        paymentRequired = "Choisissez un paiement.",
        amountInvalid = "Montant de remboursement invalide.",
        processed = "Remboursement enregistré.",
        wasteProcessed = "Perte enregistrée.",
        refunded = "Remboursé",
        writtenOff = "Perte"
    )
    AppLanguage.NL -> RefundStrings(
        refund = "Terugbetalen", title = "Terugbetaling / verlies",
        intro = "Cookit Cloud orkestreert in aanmerking komende volledige terugbetalingen: eerst de FDM-correctie, daarna compenserende loyaliteitsomkering. Gedeeltelijke fiscale/loyaliteitsterugbetalingen blijven geblokkeerd.",
        payment = "Betaling", reason = "Reden", chooseReason = "Kies een reden",
        full = "Volledig", partial = "Gedeeltelijk", waste = "Verlies / waste",
        wasteHelp = "Alleen interne afschrijving: er wordt geen geld aan de klant terugbetaald.",
        settlementHelp = "Kaart/terminalbetaling: voer eerst de terugbetaling uit op de externe terminal of PSP. Cookit registreert daarna de operatie.",
        half = "Helft", fixed = "Vast bedrag", custom = "Aangepast", amount = "Bedrag", notes = "Notities",
        confirm = "Bevestigen", close = "Sluiten",
        fiscalBlocked = "Fiscale correctie vereist vóór terugbetaling.",
        fiscalFullUnsupported = "Deze gefiscaliseerde verkoop valt buiten het bewezen P3B-contract voor volledige terugbetaling.",
        fiscalPartialUnsupported = "Gedeeltelijke terugbetaling van een gefiscaliseerde verkoop blijft geblokkeerd tot exacte lijn-/hoeveelheidstoewijzing beschikbaar is.",
        fiscalPending = "De fiscale terugbetalingscorrectie is naar de FDM gestuurd. Cookit rondt de terugbetaling af na fiscalisatie.",
        fiscalFailed = "De fiscale terugbetalingscorrectie is mislukt. Los de fiscale transactie op vóór geld wordt teruggegeven.",
        loyaltyBlocked = "Exacte loyaliteitsomkering vereist vóór terugbetaling.",
        loyaltyPartialUnsupported = "Gedeeltelijke terugbetaling met loyaliteit blijft geblokkeerd tot een exacte proportionele omkering beschikbaar is.",
        alreadyProcessed = "Voor deze betaling is al een terugbetaling/verlies geregistreerd.",
        notAllowed = "Deze terugbetaling is momenteel niet toegestaan.",
        reasonRequired = "Kies een reden.", paymentRequired = "Kies een betaling.", amountInvalid = "Ongeldig terugbetalingsbedrag.",
        processed = "Terugbetaling geregistreerd.", wasteProcessed = "Verlies geregistreerd.", refunded = "Terugbetaald", writtenOff = "Verlies"
    )
    AppLanguage.EN -> RefundStrings(
        refund = "Refund", title = "Refund / waste",
        intro = "Cookit Cloud orchestrates eligible full refunds: FDM correction first, then compensating Loyalty reversal. Partial fiscal/Loyalty refunds remain blocked until exact allocation is available.",
        payment = "Payment", reason = "Reason", chooseReason = "Choose a reason",
        full = "Full", partial = "Partial", waste = "Waste / write-off",
        wasteHelp = "Internal write-off only: no money is returned to the customer.",
        settlementHelp = "Card/terminal payment: complete the refund on the external terminal or PSP first. Cookit then records the operation.",
        half = "Half", fixed = "Fixed amount", custom = "Custom", amount = "Amount", notes = "Notes",
        confirm = "Confirm", close = "Close",
        fiscalBlocked = "A fiscal correction is required before refunding this payment.",
        fiscalFullUnsupported = "This fiscalized sale is outside the proven P3B full-refund contract.",
        fiscalPartialUnsupported = "Partial refund of a fiscalized sale remains blocked until exact line/quantity allocation is persisted.",
        fiscalPending = "The fiscal refund correction was sent to the FDM. Cookit will finalize the refund after fiscalization.",
        fiscalFailed = "The fiscal refund correction failed. Resolve the fiscal transaction before returning customer money.",
        loyaltyBlocked = "An exact Loyalty reversal is required before refunding this payment.",
        loyaltyPartialUnsupported = "Partial refund with Loyalty remains blocked until an exact proportional reversal is available.",
        alreadyProcessed = "A refund/write-off has already been recorded for this payment.",
        notAllowed = "This refund is not allowed in the current state.",
        reasonRequired = "Choose a reason.", paymentRequired = "Choose a payment.", amountInvalid = "Invalid refund amount.",
        processed = "Refund recorded.", wasteProcessed = "Write-off recorded.", refunded = "Refunded", writtenOff = "Waste"
    )
    AppLanguage.DE -> RefundStrings(
        refund = "Erstatten", title = "Erstattung / Verlust",
        intro = "Cookit Cloud orchestriert geeignete vollständige Erstattungen: zuerst die FDM-Korrektur, danach die kompensierende Loyalty-Rückbuchung. Teilweise fiskalische/Loyalty-Erstattungen bleiben gesperrt.",
        payment = "Zahlung", reason = "Grund", chooseReason = "Grund wählen",
        full = "Vollständig", partial = "Teilweise", waste = "Verlust / Waste",
        wasteHelp = "Nur interne Abschreibung: dem Kunden wird kein Geld zurückgegeben.",
        settlementHelp = "Karten-/Terminalzahlung: führen Sie die Erstattung zuerst am externen Terminal oder PSP durch. Cookit erfasst danach den Vorgang.",
        half = "Hälfte", fixed = "Fester Betrag", custom = "Benutzerdefiniert", amount = "Betrag", notes = "Notizen",
        confirm = "Bestätigen", close = "Schließen",
        fiscalBlocked = "Vor der Erstattung ist eine fiskalische Korrektur erforderlich.",
        fiscalFullUnsupported = "Dieser fiskalisierte Verkauf liegt außerhalb des nachgewiesenen P3B-Vertrags für vollständige Erstattungen.",
        fiscalPartialUnsupported = "Teilweise Erstattungen fiskalisierter Verkäufe bleiben bis zur exakten Zeilen-/Mengenaufteilung gesperrt.",
        fiscalPending = "Die fiskalische Erstattungskorrektur wurde an das FDM gesendet. Cookit schließt die Erstattung nach der Fiskalisierung ab.",
        fiscalFailed = "Die fiskalische Erstattungskorrektur ist fehlgeschlagen. Klären Sie die Fiskaltransaktion vor der Geldauszahlung.",
        loyaltyBlocked = "Vor der Erstattung ist eine exakte Loyalty-Rückbuchung erforderlich.",
        loyaltyPartialUnsupported = "Teilweise Erstattungen mit Loyalty bleiben bis zu einer exakten proportionalen Rückbuchung gesperrt.",
        alreadyProcessed = "Für diese Zahlung wurde bereits eine Erstattung/Abschreibung erfasst.",
        notAllowed = "Diese Erstattung ist derzeit nicht zulässig.",
        reasonRequired = "Wählen Sie einen Grund.", paymentRequired = "Wählen Sie eine Zahlung.", amountInvalid = "Ungültiger Erstattungsbetrag.",
        processed = "Erstattung erfasst.", wasteProcessed = "Verlust erfasst.", refunded = "Erstattet", writtenOff = "Verlust"
    )
}
